name: Run Unit Tests

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  RunUnitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Compile Solidity and Typescript
        run: |
          npm run clean
          npm run compile
      - name: Run tests
        run: |
          ALCHEMY_API_KEY="${{ secrets.ALCHEMY_API_KEY }}" \
          INFURA_URL="${{ secrets.INFURA_URL }}" \
          ETH_HARDHAT_ACCOUNT_MNEMONIC="${{ secrets.ETH_HARDHAT_ACCOUNT_MNEMONIC }}" \
          npm run test
