name: Run Linter and Formatter

on:

  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:

  RunLinterAndFormatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install frontend dependencies
        run: |
          npm install
          npm i yarn
          yarn install
      - name: Run tests
        run: |
          yarn prettier:solidity
          yarn solhint
        
